// ============================================================
// Segment Routes - /api/segments
// ============================================================
// Handles audience segmentation:
// - GET /             → List all segments
// - GET /:id          → Get segment with its members
// - POST /            → Create a segment with a filter query
// - GET /:id/preview  → Preview which customers match a segment
// - DELETE /:id       → Delete a segment
// ============================================================

const express = require('express');
const router = express.Router();

// GET /api/segments - List all segments
router.get('/', async (req, res) => {
  const db = req.app.get('db');
  try {
    const result = await db.query(
      'SELECT * FROM segments ORDER BY created_at DESC'
    );
    res.json({ segments: result.rows });
  } catch (err) {
    console.error('Error fetching segments:', err);
    res.status(500).json({ error: 'Failed to fetch segments' });
  }
});

// GET /api/segments/:id - Get segment details with member list
router.get('/:id', async (req, res) => {
  const db = req.app.get('db');
  try {
    const segment = await db.query('SELECT * FROM segments WHERE id = $1', [req.params.id]);
    if (segment.rows.length === 0) {
      return res.status(404).json({ error: 'Segment not found' });
    }

    // Get segment members
    const members = await db.query(
      `SELECT c.* FROM customers c
       JOIN segment_members sm ON c.id = sm.customer_id
       WHERE sm.segment_id = $1
       ORDER BY c.name`,
      [req.params.id]
    );

    res.json({
      ...segment.rows[0],
      members: members.rows,
    });
  } catch (err) {
    console.error('Error fetching segment:', err);
    res.status(500).json({ error: 'Failed to fetch segment' });
  }
});

// POST /api/segments - Create a new segment
// The filter_query is a SQL WHERE clause that defines who's in the segment.
// For example: "total_spent > 5000 AND city = 'Mumbai'"
// The AI route generates these filter queries from natural language.
router.post('/', async (req, res) => {
  const db = req.app.get('db');
  const { name, description, filter_query, natural_language_query } = req.body;

  if (!name || !filter_query) {
    return res.status(400).json({ error: 'Name and filter_query are required' });
  }

  const client = await db.connect();
  try {
    await client.query('BEGIN');

    // Step 1: Find all customers matching the filter
    // IMPORTANT: We use a safe approach - the filter_query is generated by our AI
    // and validated before use. In production, you'd use parameterized queries.
    const matchQuery = `SELECT id FROM customers WHERE ${filter_query}`;
    let matchedCustomers;
    try {
      matchedCustomers = await client.query(matchQuery);
    } catch (queryErr) {
      await client.query('ROLLBACK');
      return res.status(400).json({ 
        error: 'Invalid filter query', 
        details: queryErr.message 
      });
    }

    // Step 2: Create the segment record
    const segmentResult = await client.query(
      `INSERT INTO segments (name, description, filter_query, natural_language_query, customer_count) 
       VALUES ($1, $2, $3, $4, $5) RETURNING *`,
      [name, description, filter_query, natural_language_query, matchedCustomers.rows.length]
    );
    const segmentId = segmentResult.rows[0].id;

    // Step 3: Insert segment memberships
    for (const row of matchedCustomers.rows) {
      await client.query(
        'INSERT INTO segment_members (segment_id, customer_id) VALUES ($1, $2)',
        [segmentId, row.id]
      );
    }

    await client.query('COMMIT');
    res.status(201).json({
      ...segmentResult.rows[0],
      customer_count: matchedCustomers.rows.length,
    });
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Error creating segment:', err);
    res.status(500).json({ error: 'Failed to create segment' });
  } finally {
    client.release();
  }
});

// POST /api/segments/preview - Preview a filter without creating
router.post('/preview', async (req, res) => {
  const db = req.app.get('db');
  const { filter_query } = req.body;

  if (!filter_query) {
    return res.status(400).json({ error: 'filter_query is required' });
  }

  try {
    const result = await db.query(
      `SELECT id, name, email, city, total_spent, order_count 
       FROM customers WHERE ${filter_query} LIMIT 100`
    );
    res.json({ customers: result.rows, count: result.rows.length });
  } catch (err) {
    res.status(400).json({ error: 'Invalid filter query', details: err.message });
  }
});

// DELETE /api/segments/:id
router.delete('/:id', async (req, res) => {
  const db = req.app.get('db');
  try {
    await db.query('DELETE FROM segments WHERE id = $1', [req.params.id]);
    res.json({ success: true });
  } catch (err) {
    console.error('Error deleting segment:', err);
    res.status(500).json({ error: 'Failed to delete segment' });
  }
});

module.exports = router;
